let dadosPagina={};let dadosFiltrados=[];let paginaAtual=1;const itensPorPagina=10;
async function carregarJSON(caminho){try{const resposta=await fetch(caminho);if(!resposta.ok)throw new Error(`Erro ao carregar ${caminho}`);return await resposta.json()}catch(erro){console.error(erro);return[]}}
function statusClasse(status){if(!status)return"status-encerrado";const s=status.toLowerCase();return s.includes("vigente")||s.includes("publicado")||s.includes("em andamento")?"status-vigente":"status-encerrado"}
function linhaArquivo(caminho){if(!caminho||caminho.trim()==="")return"Não anexado";return`<a href="${caminho}" target="_blank" class="botao">Acessar</a>`}
function linhaDetalhes(caminho){if(!caminho||caminho.trim()==="")return"-";return`<a href="${caminho}" class="botao-secundario">Ver detalhes</a>`}
function preencherData(){const el=document.getElementById("dataHoje");if(el){const hoje=new Date();el.innerHTML=hoje.toLocaleDateString("pt-BR")+" às "+hoje.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}}
function aplicarBuscaNosDados(dados,termo){if(!termo)return dados;return dados.filter(item=>JSON.stringify(item).toLowerCase().includes(termo.toLowerCase()))}
function filtrarTabelas(){const termo=document.getElementById("campoBusca")?.value||"";if(window.tipoPagina==="cargos"){dadosFiltrados=aplicarBuscaNosDados(dadosPagina.remuneracao||[],termo);paginaAtual=1;preencherRemuneracao();return}document.querySelectorAll("tbody tr").forEach(linha=>{linha.style.display=linha.innerText.toLowerCase().includes(termo.toLowerCase())?"":"none"})}
function preencherRemuneracao(){const tabela=document.getElementById("tabelaRemuneracao");if(!tabela)return;if(!dadosFiltrados.length){tabela.innerHTML=`<tr><td colspan="6" class="linha-vazia">Nenhum cargo localizado para o filtro informado.</td></tr>`;atualizarPaginacao();return}const inicio=(paginaAtual-1)*itensPorPagina;const pagina=dadosFiltrados.slice(inicio,inicio+itensPorPagina);tabela.innerHTML=pagina.map(item=>`<tr><td>${item.area}</td><td>${item.cargo}</td><td>${item.natureza}</td><td>${item.vagas}</td><td>${item.cargaHoraria}</td><td>${item.remuneracao}</td></tr>`).join("");atualizarPaginacao()}
function atualizarPaginacao(){const info=document.getElementById("infoPagina");if(!info)return;const totalPaginas=Math.max(1,Math.ceil(dadosFiltrados.length/itensPorPagina));info.innerText=`Página ${paginaAtual} de ${totalPaginas}`}
function paginaAnterior(){if(paginaAtual>1){paginaAtual--;preencherRemuneracao()}}
function proximaPagina(){const totalPaginas=Math.max(1,Math.ceil(dadosFiltrados.length/itensPorPagina));if(paginaAtual<totalPaginas){paginaAtual++;preencherRemuneracao()}}
function preencherTabelaSimples(idTabela,dados,colunas,mensagemVazia){const tabela=document.getElementById(idTabela);if(!tabela)return;if(!dados.length){tabela.innerHTML=`<tr><td colspan="${colunas.length}" class="linha-vazia">${mensagemVazia}</td></tr>`;return}tabela.innerHTML=dados.map(item=>`<tr>${colunas.map(c=>{if(c.tipo==="status")return`<td><span class="status ${statusClasse(item[c.campo])}">${item[c.campo]}</span></td>`;if(c.tipo==="arquivo")return`<td>${linhaArquivo(item[c.campo])}</td>`;if(c.tipo==="detalhes")return`<td>${linhaDetalhes(item[c.campo])}</td>`;return`<td>${item[c.campo]}</td>`}).join("")}</tr>`).join("")}
async function iniciarPagina(){preencherData();if(window.tipoPagina==="cargos"){dadosPagina.remuneracao=await carregarJSON("dados/remuneracao.json");dadosFiltrados=dadosPagina.remuneracao;preencherRemuneracao()}if(window.tipoPagina==="estagiarios-terceirizados"){preencherTabelaSimples("tabelaEstagiarios",await carregarJSON("dados/estagiarios.json"),[{campo:"ano"},{campo:"nome"},{campo:"dataContratacao"},{campo:"dataTermino"},{campo:"situacao",tipo:"status"},{campo:"observacao"}],"Não houve contratação de estagiários no período consultado.");preencherTabelaSimples("tabelaTerceirizados",await carregarJSON("dados/terceirizados.json"),[{campo:"ano"},{campo:"nome"},{campo:"funcao"},{campo:"empresa"},{campo:"situacao",tipo:"status"},{campo:"observacao"}],"Não houve contratação de terceirizados no período consultado.")}if(window.tipoPagina==="processos-seletivos"){preencherTabelaSimples("tabelaProcessos",await carregarJSON("dados/processos-seletivos.json"),[{campo:"ano"},{campo:"numero"},{campo:"objeto"},{campo:"dataPublicacao"},{campo:"situacao",tipo:"status"},{campo:"detalhes",tipo:"detalhes"}],"Não houve processos seletivos no período consultado.")}if(window.tipoPagina==="concursos"){preencherTabelaSimples("tabelaConcursos",await carregarJSON("dados/concursos-publicos.json"),[{campo:"ano"},{campo:"numero"},{campo:"objeto"},{campo:"dataPublicacao"},{campo:"situacao",tipo:"status"},{campo:"detalhes",tipo:"detalhes"}],"Não houve concursos públicos no período consultado.")}if(window.tipoPagina==="detalhe-processo"){preencherTabelaSimples("tabelaDocumentos",await carregarJSON(window.arquivoDadosDetalhe),[{campo:"ordem"},{campo:"tipo"},{campo:"descricao"},{campo:"data"},{campo:"situacao",tipo:"status"},{campo:"arquivo",tipo:"arquivo"}],"Não há documentos cadastrados para este processo.")}if(window.tipoPagina==="detalhe-concurso"){preencherTabelaSimples("tabelaDocumentos",await carregarJSON(window.arquivoDadosDetalhe),[{campo:"ordem"},{campo:"tipo"},{campo:"descricao"},{campo:"data"},{campo:"situacao",tipo:"status"},{campo:"arquivo",tipo:"arquivo"}],"Não há documentos cadastrados para este concurso.")}}
function obterDadosDasTabelas(){const dados=[];document.querySelectorAll(".bloco").forEach(bloco=>{const titulo=bloco.querySelector("h3")?.innerText||"Seção";const tabela=bloco.querySelector("table");if(!tabela)return;const cabecalhos=Array.from(tabela.querySelectorAll("thead th")).map(th=>th.innerText.trim());tabela.querySelectorAll("tbody tr").forEach(tr=>{if(tr.style.display==="none")return;const colunas=Array.from(tr.querySelectorAll("td")).map(td=>td.innerText.trim());if(colunas.length===cabecalhos.length){const item={secao:titulo};cabecalhos.forEach((c,i)=>item[c]=colunas[i]);dados.push(item)}})});return dados}
function baixarArquivo(conteudo,nomeArquivo,tipo){const blob=new Blob([conteudo],{type:tipo});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=nomeArquivo;link.click()}
function nomeBase(){return document.title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function exportarCSV(){const dados=obterDadosDasTabelas();if(!dados.length)return alert("Nenhum dado disponível para exportação.");const colunas=Object.keys(dados[0]);const linhas=[colunas.join(";"),...dados.map(item=>colunas.map(coluna=>`"${String(item[coluna]??"").replace(/"/g,'""')}"`).join(";"))];baixarArquivo("\uFEFF"+linhas.join("\n"),nomeBase()+".csv","text/csv;charset=utf-8;")}
function exportarJSON(){baixarArquivo(JSON.stringify(obterDadosDasTabelas(),null,2),nomeBase()+".json","application/json;charset=utf-8;")}
function exportarXML(){const dados=obterDadosDasTabelas();let xml=`<?xml version="1.0" encoding="UTF-8"?>\n<registros>\n`;dados.forEach(item=>{xml+="  <registro>\n";Object.entries(item).forEach(([chave,valor])=>{const tag=chave.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]/g,"_").toLowerCase();xml+=`    <${tag}>${String(valor).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}</${tag}>\n`});xml+="  </registro>\n"});xml+="</registros>";baixarArquivo(xml,nomeBase()+".xml","application/xml;charset=utf-8;")}
function exportarXLSX(){const dados=obterDadosDasTabelas();if(!dados.length)return alert("Nenhum dado disponível para exportação.");const planilha=XLSX.utils.json_to_sheet(dados);const pasta=XLSX.utils.book_new();XLSX.utils.book_append_sheet(pasta,planilha,"Dados");XLSX.writeFile(pasta,nomeBase()+".xlsx")}
function exportarPDF(){const dados=obterDadosDasTabelas();const{jsPDF}=window.jspdf;const doc=new jsPDF("landscape");doc.setFontSize(14);doc.text(document.title,14,15);if(!dados.length){doc.text("Nenhum dado disponível para exportação.",14,30);doc.save(nomeBase()+".pdf");return}const colunas=Object.keys(dados[0]);const linhas=dados.map(item=>colunas.map(coluna=>item[coluna]));doc.autoTable({head:[colunas],body:linhas,startY:25,styles:{fontSize:7,cellPadding:2},headStyles:{fillColor:[7,55,99]}});doc.save(nomeBase()+".pdf")}
iniciarPagina();